apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springapp
  name: springapp
  namespace: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: springapp
    spec:
      containers:
      - image: amrith501/restapi:01
        ports:
            - containerPort: 8080
        env:   # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  host

          - name: DB_NAME  # Setting Database name from configMap
              valueFrom :
                configMapKeyRef :
                  name : db-config
                  key :  dbName

          - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  username

          - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom :
                secretKeyRef :
                  name : mysql-secrets
                  key :  password
